# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
workflows:
  build_test:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - 12.18.3
      - build_docker_image:
          requires:
            - node/test

jobs:
  build_docker_image:
    docker:
      - image: cimg/node:12.18.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set up tag
          command: echo "export TAG=0.1.$CIRCLE_SHA1" >> $BASH_ENV
      - run: 
          name: Build Docker image
          command: |
            docker build -t ci-image:latest .

orbs:
  node: circleci/node@4.5.0
